package example:plugin;

interface plugin-interface {
  resource extension-state {
    constructor();
    index: func() -> u32;
    set-index: func(i: u32);
  }

  add: func(a: u32, b: u32) -> u32;
  parse: func(bytes: list<u8>) -> extension-state;
}


interface host-interface {
  host-test: func() -> bool;
}

world plugin {
  import host-interface;

  export plugin-interface;
}
