package example:pluggable;

use example:plugin/plugin-interface;

interface plugin-set {
  get: func(index: u32) -> option<plugin-interface>;
  count: func() -> u32;
}

interface pluggable-interface {
  run: func(input: list<u8>) -> bool;
}

world pluggable {
  import plugin-set;
  
  export pluggable-interface;
}
