package example:pluggable;

interface pluggable-interface {
  run: func(input: list<u8>) -> bool;
}

// Copied from *plugin_api/* because
// `wasmtime::component::bindgen!` doesn't allow searching
// multiple `path`s for WIT files.
interface plugin-interface {
  resource extension-state {
    constructor();
    index: func() -> u32;
    set-index: func(i: u32);
  }

  add: func(a: u32, b: u32) -> u32;
  parse: func(bytes: list<u8>) -> extension-state;
}

interface host-interface {
  use plugin-interface.{extension-state};
  
  plugins-len: func() -> u32;
  run-plugin: func(index: u32, input: list<u8>) -> extension-state;
}

world pluggable {
  import host-interface;
  export pluggable-interface;
}
